correct_answer={
'01':'Knee',
'02':'Iago',
'03':'Tin',
'04':'All the Presidents Men',
'05':'3',
'06':'Olivia',
'07':'Simon Amstell',
'08':'Call of Duty',
'09':'Tennessee',
'10':'Nine Inch Nails',
'11':'Krone',
'12':'The French Open (Roland Garros)',
'13':'Netherlands',
'14':'Four (The Godfather Part 2, Heat, Righteous Kill, The Irishman)',
'15':'Marathon',
'16':'Emperor Hirohito',
'17':'Mercury',
'18':'Gillian Flynn',
'19':'Salvador Dali',
'20':'Queens Park Rangers',
}