questions={'01':'In which part of your body would you find the cruciate ligament? 1-hand  2-Knee  3-feet 4head ',
'02':'What is the name of the main antagonist in the Shakespeare play Othello? 1-Iago  2-smith 3-stive 4-dave ',
'03':'What element is denoted by the chemical symbol Sn in the periodic table?  1-Tin  2-fill 3-kill 4-stab ',
'04':'What is the name of the 1976 film about the Watergate scandal, starring Robert Redford and Dustin Hoffman?  1-king of stone 2-All the Presidents Men 3-avengers 4-kiiler',
'05':'How many of Henry VIIIs wives were called Catherine? 1-4 2-7 3-2 4-3',
'06':'What was the most popular girls name in the UK in 2019? 1-emma 2-alice 3-Olivia 4-sara',
'07':'Which comedian was the second permanent host of Never Mind the Buzzcocks after Mark Lamarr? 1-Simon Amstell 2-jame hill 3-stive jay 4-tom parker',
'08':'Which popular video game franchise has released games with the subtitles World At War and Black Ops? 1-until down 2-Call of Duty 3-hitman 4-watch dogs',
'09':'In what US State is the city Nashville? 1-los angeles 2-washengtown 3-rome 4-Tennessee',
'10':'Which rock band was founded by Trent Reznor in 1988? 1-Nine Inch Nails 2-five Inch Nails 3-seven Inch Nails 4-ten Inch Nails',
'11':'What is the currency of Denmark? 1-doller 2-Krone 3-euro 4-riyal',
'12':'Which Tennis Grand Slam is played on a clay surface?  1-The French Open (Roland Garros) 2-The French Open (jokovic) 3-The French Open (nedved) 4-The French Open (nadal)',
'13':'In which European country would you find the Rijksmuseum? 1-england 2-germany 3-france 4-Netherlands',
'14':'How many films have Al Pacino and Robert De Niro appeared in together? 1-2  2-4  3-5  4-3',
'15':'What was the old name for a Snickers bar before it changed in 1990? 1-100m  2-Marathon 3-chogan 3-500m ',
'16':'Who was the head of state in Japan during the second world war? 1-mandela 2-hitller 3-Emperor Hirohito 4-smith jay',
'17':'What is the smallest planet in our solar system? 1-earth 2-Mercury 3-mars 4-venus ',
'18':'Who wrote the novels Gone Girl and Sharp Objects? 1-Gillian Flynn 2-matt haig 3- stephen king 4-pat barker',
'19':'Which legendary surrealist artist is famous for painting melting clocks? 1-gala dali 2-Salvador Dali 3-picasso 4-magritte',
'20':'Which football club plays its home games at Loftus Road? 1-shalke 2-santos 3-Queens Park Rangers 4-psg'
}
